[pytest]
addopts = --strict-config --strict-markers
testpaths = tests/unit tests/integration
filterwarnings =
    error::UserWarning:medparse\..*
    ignore::UserWarning:pdfminer\..*
    ignore::UserWarning:pdfplumber\..*
