indications_for_use:
  - "indications"
  - "indication"
  - "indications for use"
  - "indication for use"
  - "clinical indications"
  - "clinical indication"
  - "intended purpose"
  - "intended purposes"
  - "application"
  - "applications"
  - "intended application"
  - "intended applications"
intended_use:
  - "intended use"
  - "intended uses"
  - "intended application"
  - "intended applications"
  - "intended purpose"
  - "intended purposes"
intended_user:
  - "intended user"
  - "intended users"
  - "user qualifications"
  - "operator qualifications"
  - "qualified operators"
intended_patient_population:
  - "intended patient population"
  - "patient population"
  - "intended patients"
