common:
  - "WARNING"
  - "CAUTION"
  - "DANGER"
  - "NOTICE"
  - "IMPORTANT"
  - "NOTE"
OLYMPUS:
  - "For Your Safety"
  - "Safety Precautions"
  - "Important Information"
ERBE:
  - "Safety instructions"
  - "Important notes"
INTUITIVE:
  - "General Warnings"
  - "Clinical Risks"
  - "Cautions"
  - "Notes"
