# Citation policy - what documents to show in references
include_doc_types:
  - journal_article
  - guideline
  - society_statement
  - systematic_review
  - meta_analysis
  - randomized_trial
  - case_report
  - case_series
  - cohort_study
  - review

exclude_doc_types:
  - textbook_chapter
  - internal_notes
  - papoip_chapter
  - practical_guide_chapter
  - bacada_chapter

max_citations: 10
min_pub_year: 2000