fixes:
  ackground: Background
  etting: Setting
  atients: Patients
  ethods: Methods
  esults: Results
  onclusions: Conclusions
  tatistical Analysis: Statistical Analysis
  ntroduction: Introduction
  iscussion: Discussion
  eferences: References
  andomization: Randomization
  tudy Protocol: Study Protocol
  tudy Outcomes: Study Outcomes
  cknowledgments: Acknowledgments